Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
sklearn.datasets.


In [53]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [54]:
from sklearn.datasets import load_iris

In [55]:
dataset = load_iris()

In [56]:
df = pd.DataFrame(dataset.data , columns = dataset.feature_names)

In [57]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [58]:
df['Target'] = dataset.target

Q2. Implement a function to standardise the features before applying KNN classifier.


In [59]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
scaler = StandardScaler()

In [62]:
X_train = scaler.fit_transform(X_test)
X_test  = scaler.transform(X_test)

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33,random_state = 42)

In [64]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape 

((100, 4), (50, 4), (100,), (50,))

In [65]:
from sklearn.neighbors import KNeighborsClassifier

In [66]:
knn = KNeighborsClassifier(n_neighbors=5 , algorithm='auto')

In [67]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [68]:
y_pred = knn.predict(X_test)

In [69]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [70]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [71]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]


Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
cross-validation on load_iris dataset in sklearn.datasets.

In [72]:
from sklearn.model_selection import GridSearchCV

In [73]:
params = {
    'n_neighbors':[1,2,3,4,5,6]
}

In [74]:
clf = GridSearchCV(knn , param_grid = params)

In [75]:
clf.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6]})

In [76]:
clf.best_params_

{'n_neighbors': 1}

Q3. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
load_iris dataset in sklearn.datasets.

In [77]:
knn = KNeighborsClassifier(n_neighbors=5 , algorithm='auto',weights='distance')

In [78]:
knn.fit(X_train,y_train)

KNeighborsClassifier(weights='distance')

In [79]:
y_pred1 = knn.predict(X_test)

In [80]:
print(accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))

0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]


Q4. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in
sklearn.datasets.

Q5. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
sklearn.datasets.

In [81]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [82]:
!pip install scikit-learn==1.0.2


In [88]:
from sklearn.datasets import load_boston
boston = load_boston()

In [89]:
bos = pd.DataFrame(boston.data , columns = boston.feature_names)

In [90]:
bos.head

<bound method NDFrame.head of         CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       1

In [93]:
bos['Target'] = boston.target

In [96]:
X = bos.iloc[:,:-1]
y = bos.iloc[:,-1]

In [98]:
from sklearn.preprocessing import StandardScaler

In [99]:
st = StandardScaler()

In [100]:
X_train = scaler.fit_transform(X_test)
X_test  = scaler.transform(X_test)

In [101]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33,random_state = 42)

In [102]:
from sklearn.neighbors import KNeighborsRegressor

In [103]:
knr = KNeighborsRegressor()

In [104]:
knr.fit(X_train,y_train)

KNeighborsRegressor()

In [105]:
y_pred = knr.predict(X_test)

In [106]:
y_pred

array([24.54, 29.34, 14.6 , 28.94, 17.44, 31.88, 20.58, 16.06, 18.02,
       21.18, 21.9 , 21.36, 12.28, 20.56, 23.7 , 21.74, 21.18, 14.06,
       33.72, 10.6 , 25.86, 29.34, 19.7 , 21.08, 18.88, 23.16, 21.88,
       12.34, 21.9 , 21.18, 22.68, 23.14, 10.3 , 30.04, 17.54, 21.12,
       21.66, 22.92, 22.52, 29.08, 21.18, 27.98, 38.82, 22.4 , 24.84,
       12.6 , 19.7 , 28.94, 19.8 , 22.22, 22.44, 34.7 , 22.04, 21.18,
       29.72, 21.38, 12.5 , 35.04, 21.82, 20.6 , 25.3 , 38.82, 28.68,
       16.26, 30.46, 24.24, 12.24, 25.3 , 35.04, 12.34, 23.94, 22.52,
       14.82, 30.38, 20.56,  8.98, 19.68, 38.82, 10.94, 15.04, 22.4 ,
       15.96, 26.3 , 12.24, 22.02, 34.  , 14.16, 22.58, 26.04, 17.86,
       24.5 , 15.22, 17.48, 21.76, 24.76, 17.86, 30.16, 10.76, 10.76,
       11.92, 21.82, 20.56, 23.16, 21.28, 22.22, 10.88, 23.96, 24.56,
       26.74, 26.3 ,  9.98, 15.74, 23.46, 33.72, 33.46, 15.22, 27.9 ,
       17.2 , 22.76, 22.44, 24.78, 31.62,  9.78, 18.74, 24.38, 23.28,
       28.28, 24.22,

In [84]:
#Q7. Write a Python function to calculate the euclidean distance between two points.
def euclidean_distance(p1, p2):
  distance = 0
  for i in range(len(p1)):
    distance += (p1[i] - p2[i])**2
  return np.sqrt(distance)


In [85]:
p1 = [1, 2]
p2 = [4, 5]

distance = euclidean_distance(p1, p2)

print(distance)

4.242640687119285


In [86]:
#Q8. Write a Python function to calculate the manhattan distance between two points.
def manhattan_distance(p1, p2):

  distance = 0
  for i in range(len(p1)):
    distance += abs(p1[i] - p2[i])
  return distance

In [87]:
p1 = [1, 2]
p2 = [4, 5]

distance = manhattan_distance(p1, p2)

print(distance)

6
